In [1]:
#question 1
import numpy as np
a = np.array([1,2,3,4,5])
print (a + 2)
print(a*3)
print(a/2)


[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [2]:
#question 2
import numpy as np
from scipy import stats
arr = np.array([1,2,3,4,5])
reverse_array = np.sort(arr)[::-1]
print(reverse_array)

X = np.array([1,2,3,4,5,1,2,1,1,1])
mode_result = stats.mode(X)
mode_value = mode_result.mode[0] if isinstance(mode_result.mode, np.ndarray) else mode_result.mode
print(mode_value)
mode_indices = np.where(X == mode_value)[0]
print(mode_indices)

Y = np.array([1,1,1,2,3,4,2,4,3,3])
mode_result1 = stats.mode(Y)
mode_value1 = mode_result1.mode[0] if isinstance(mode_result1.mode, np.ndarray) else mode_result1.mode
print(mode_value1)
mode_indices1 = np.where(Y == mode_value1)[0]
print(mode_indices1)

[5 4 3 2 1]
1
[0 5 7 8 9]
1
[0 1 2]


In [3]:
#question 3:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,1])
print(arr[2,0])

20
70


In [5]:
#question 4:
import numpy as np
Nikhil = np.linspace(10,100,25)
print("dimensions: ", Nikhil.ndim)
print("shape: ", Nikhil.shape)
print("Total Elements: ", Nikhil.size)
print("Data types: ", Nikhil.dtype)
print("Total bytes consumed: ", Nikhil.nbytes)

transpose = Nikhil.reshape(Nikhil.shape[0], 1)

tranpose_without_shape = Nikhil.T

print("transpose: ", transpose)
print("transpose without shape: ", tranpose_without_shape)

dimensions:  1
shape:  (25,)
Total Elements:  25
Data types:  float64
Total bytes consumed:  200
transpose:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
transpose without shape:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
#question : 5
import numpy as np
ucs420_Nikhil = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print(np.mean(ucs420_Nikhil))
print(np.median(ucs420_Nikhil))
print(np.max(ucs420_Nikhil))
print(np.min(ucs420_Nikhil))
print(np.unique(ucs420_Nikhil))

reshaped_ucs420_Nikhil = ucs420_Nikhil.reshape(4,3)
print(reshaped_ucs420_Nikhil)

resized_ucs420_Nikhil = np.resize(ucs420_Nikhil, (2,3))
print(resized_ucs420_Nikhil)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
