In [1]:
#Q1

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("original array ", arr)
print("adding 2 ", arr + 2)
print("multiplying by 3 ", arr * 3)
print("dividing by 2 ", arr / 2)


original array  [1 2 3 4 5]
adding 2  [3 4 5 6 7]
multiplying by 3  [ 3  6  9 12 15]
dividing by 2  [0.5 1.  1.5 2.  2.5]


In [2]:
#Q2a

import numpy as np
arr2 = np.array([1, 2, 3, 6, 4, 5])
print("reversed array", arr2[::-1])

reversed array [5 4 6 3 2 1]


In [3]:
# Q2b

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
print(np.bincount(x).argmax(), np.bincount(y).argmax())


1 1


In [4]:
#Q3

import numpy as np
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr3[0, 1], arr3[2, 0])

20 70


In [5]:
#Q4

import numpy as np
Ansh_array = np.linspace(10, 100, 25)
print(Ansh_array.shape)
print(Ansh_array.size)
print(Ansh_array.dtype)
print(Ansh_array.nbytes)
print(Ansh_array.reshape(25, 1).T)


(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


In [6]:
#Q5

import numpy as np
arr5 = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(np.mean(arr5))
print(np.median(arr5))
print(np.max(arr5))
print(np.min(arr5))
print(np.unique(arr5))
reshaped_arr5 = arr5.reshape(4, 3)
resized_arr5 = np.resize(arr5, (2, 3))
print(reshaped_arr5, resized_arr5)


43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]] [[10 20 30]
 [40 50 60]]
